const $=id=>document.getElementById(id);let selected=null,job=null,busy=false,started=0,ticker=null,view='source';
const titles={source:'Original image',boxes:'Grounding boxes',outlines:'Segmentation outlines',masks:'Instance masks'};
const notes={source:'The actual uploaded RGB image',boxes:'Filtered detector proposals',outlines:'SAM masks over the source',masks:'Colours identify predicted objects'};
function error(message){$('feedback').textContent=message;$('feedback').hidden=!message}
async function json(url,options){const r=await fetch(url,options);if(!r.ok){let e;try{e=await r.json()}catch{}throw Error(typeof e?.detail==='string'?e.detail:`Request failed (${r.status}).`)}return r.json()}
function controls(){['choose','replace','category','mode','threshold'].forEach(id=>$(id).disabled=busy);document.querySelectorAll('[data-sample]').forEach(b=>b.disabled=busy);$('run').disabled=busy||!selected}
function clear(){job=null;$('result').hidden=true;$('view-tabs').hidden=true;$('stages').replaceChildren();error('');if(selected){$('preview').src=selected.preview;view='source'}}
async function upload(file){if(!file||busy)return;busy=true;controls();clear();try{const f=new FormData();f.append('file',file);selected=await json('/api/images',{method:'POST',body:f});$('filename').textContent=selected.name;$('fileinfo').textContent=`${selected.width} × ${selected.height} px · RGB appearance only`;$('preview').src=selected.preview;$('preview').hidden=false;$('empty').hidden=true;$('replace').hidden=false;$('expand').hidden=false}catch(e){error(e.message)}finally{busy=false;controls()}}
$('choose').onclick=$('replace').onclick=()=>$('file').click();$('file').onchange=()=>{upload($('file').files[0]);$('file').value=''};
document.querySelectorAll('[data-sample]').forEach(b=>b.onclick=async()=>{try{const r=await fetch('/api/samples/'+b.dataset.sample);if(!r.ok)throw Error('Sample unavailable');$('category').value=b.dataset.sample;await upload(new File([await r.blob()],b.dataset.sample+'.png',{type:'image/png'}))}catch(e){error(e.message)}});
const savedTheme=localStorage.getItem('satquery-lab-theme');if(savedTheme==='light')document.documentElement.dataset.theme='light';$('theme').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('satquery-lab-theme',next)};
$('threshold').oninput=()=>{$('threshold-value').value=Number($('threshold').value).toFixed(2)};
function showView(v){if(!job)return;view=v;$('preview').src=`/api/runs/${job.id}/${v}`;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('expand').onclick=()=>{$('full').src=$('preview').src;$('dialog').showModal()};$('close').onclick=()=>$('dialog').close();
function element(tag,text,parent,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;if(parent)parent.append(e);return e}
function metric(value,label){const e=element('div','',$('metrics'),'metric');element('b',value,e);element('span',label,e)}
function render(j){job=j;const r=j.result;$('result').hidden=false;$('view-tabs').hidden=false;$('metrics').replaceChildren();metric(r.objects,'objects proposed');metric(r.mode==='both'?`${r.union_mask_percent.toFixed(2)}%`:'—','predicted mask coverage');$('summary').textContent=r.objects?`${r.category} · ${r.segmented_objects} ${r.segmented_objects===1?'outline':'outlines'} generated · ${r.seconds.toFixed(1)} s model pipeline${r.capped?' · object limit reached':''}`:'No candidates passed these settings. This does not prove that the object is absent.';
for(const [id,artifact] of [['bundle','bundle'],['record','record'],['arrays','arrays'],['instances','instances']])$(id).href=`/api/runs/${j.id}/${artifact}`;
$('arrays').hidden=$('instances').hidden=r.mode==='boxes';$('stages').replaceChildren();for(const key of Object.keys(titles)){const button=document.createElement('button');button.className='stage';const im=document.createElement('img');im.src=`/api/runs/${j.id}/${key}`;im.alt=titles[key];button.append(im);const caption=element('span',titles[key],button);element('small',r.mode==='boxes'&&['outlines','masks'].includes(key)?'Segmentation not selected':notes[key],caption);button.onclick=()=>{showView(key);$('full').src=im.src;$('dialog').showModal()};$('stages').append(button)}
$('steps').replaceChildren();for(const t of r.trace)element('li',`${t.step} · ${t.seconds.toFixed(2)} s`,$('steps'));
$('calculation').replaceChildren();element('p',`Detector score ≥ ${r.settings.box_threshold.toFixed(2)}; text score ≥ ${r.settings.text_threshold.toFixed(2)}. Duplicate boxes are suppressed when overlap area ÷ union area exceeds ${r.settings.nms_iou}.`,$('calculation'));element('p',`Scene-sized proposals and redundant enclosing boxes are filtered. ${r.raw_candidates} raw proposals → ${r.objects} retained. Raw boxes and filter settings are included in Run JSON.`,$('calculation'));element('p',r.mode==='both'?`Mask coverage = ${r.union_mask_pixels.toLocaleString()} pixels in the combined masks ÷ ${r.total_image_pixels.toLocaleString()} image pixels × 100 = ${r.union_mask_percent.toFixed(2)}%. Overlap is counted once. This is predicted image-pixel coverage, not ground area.`:'Segmentation was not selected; mask coverage was not calculated.',$('calculation'));
$('objects').replaceChildren();for(const d of r.detections){const row=element('div','',$('objects'),'object');element('b',`Object ${d.id} · ${r.category}`,row);element('div',`Detector score ${d.detector_score.toFixed(3)}${d.sam_predicted_iou!==undefined?' · SAM quality score '+d.sam_predicted_iou.toFixed(3):''}`,row);element('div',`Box [left, top, right, bottom]: ${d.box_xyxy.map(v=>v.toFixed(1)).join(', ')} px`,row);if(d.mask_pixels!==undefined)element('div',`${d.mask_pixels.toLocaleString()} predicted mask pixels`,row)}if(!r.objects)element('p','No retained objects.',$('objects'));
$('details').replaceChildren();for(const [k,v] of [['Run',j.id],['Source',j.image.name],['SHA-256',j.image.sha256],['Prompt',r.prompt],['Device',`Local GPU · peak ${r.peak_gpu_GiB} GiB`],['Model weights','Float32 · pretrained · no new training'],...r.models.flatMap(m=>[[m.model,m.revision],['License',m.license]])]){element('dt',k,$('details'));element('dd',v,$('details'))}$('limitations').replaceChildren();r.limitations.forEach(s=>element('li',s,$('limitations')));showView(r.mode==='both'?'outlines':'boxes')}
$('form').onsubmit=async e=>{e.preventDefault();if(busy||!selected)return;clear();busy=true;controls();started=Date.now();$('progress').hidden=false;$('stage').textContent='Starting isolated worker';ticker=setInterval(()=>{$('elapsed').textContent=`Elapsed ${Math.floor((Date.now()-started)/1000)} s · first run may take longer`},500);try{let j=await json('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_id:selected.id,category:$('category').value,mode:$('mode').value,threshold:Number($('threshold').value)})});while(j.state==='running'){if(Date.now()-started>660000)throw Error('Run polling timed out.');await new Promise(r=>setTimeout(r,1000));j=await json('/api/runs/'+j.id);$('stage').textContent=j.stage||'Preparing evidence'}if(j.state==='error')throw Error(j.error);render(j)}catch(e){error(e.message)}finally{clearInterval(ticker);$('progress').hidden=true;busy=false;controls();status()}};
async function status(){try{const s=await json('/api/status');$('status').textContent=s.busy?'Local lab · Processing':'Local lab · Ready'}catch{$('status').textContent='Local lab · Offline'}}status();setInterval(status,5000);
$('viewer').ondragover=e=>e.preventDefault();$('viewer').ondrop=e=>{e.preventDefault();upload(e.dataTransfer.files[0])};

['category','mode'].forEach(id=>$(id).onchange=()=>clear());

