const $=id=>document.getElementById(id);
let image=null,busy=false,currentRun=null,scale=1,offset={x:0,y:0},pointer=null;
let theme=localStorage.getItem('satquery-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
function setTheme(){document.documentElement.dataset.theme=theme;$('theme').textContent=theme==='dark'?'☀':'☾';$('theme').setAttribute('aria-label',`Switch to ${theme==='dark'?'light':'dark'} mode`);localStorage.setItem('satquery-theme',theme)}setTheme();$('theme').onclick=()=>{theme=theme==='dark'?'light':'dark';setTheme()};
async function api(url,options){const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'The request could not be completed.');return d}
function feedback(message=''){$('feedback').textContent=message;$('feedback').hidden=!message}
function controls(){if($('scene-sample'))$('scene-sample').disabled=busy;if($('ndvi-threshold'))$('ndvi-threshold').disabled=busy;$('analyze').disabled=busy||!image||!$('question').value.trim();$('replace').disabled=busy;$('choose').disabled=busy;$('sample').disabled=busy;$('question').disabled=busy;$('mode').disabled=busy;document.querySelectorAll('.suggestion').forEach(b=>b.disabled=busy)}
async function status(){try{const s=await api('/api/status');$('status').textContent=`Local model · ${s.state==='processing'?'Processing':s.state==='ready'?'Ready':'Loads on first run'}`}catch{$('status').textContent='Local server · Offline'}}status();setInterval(status,5000);
$('question').oninput=()=>{$('counter').textContent=`${$('question').value.length}/500`;controls()};
for(const id of ['choose','replace'])$(id).onclick=()=>$('file').click();$('file').onchange=()=>{if($('file').files[0])upload($('file').files[0]);$('file').value=''};
async function upload(file){if(busy)return;if(file.size>20*1024*1024)return feedback('Please choose an image smaller than 20 MB.');busy=true;controls();feedback();try{const form=new FormData();form.append('file',file);const next=await api('/api/images',{method:'POST',body:form});image=next;clearEvidence();$('geo-info').textContent=next.geo ? [next.geo.crs||'No CRS',next.geo.resolution.join(' × ')+' CRS units/pixel',next.geo.acquired||'Date unavailable','Bands: '+Object.keys(next.geo.bands).join(', ')].join(' · ') : 'RGB image: spectral measurements unavailable';$('satellite').src=next.preview;$('satellite').hidden=false;$('empty').hidden=true;$('image-tools').hidden=false;$('zoom-label').hidden=false;$('replace').hidden=false;$('filename').textContent=next.name;$('fileinfo').textContent=`${next.width} × ${next.height} px · ${(next.bytes/1024/1024).toFixed(2)} MB`;$('idle-state').hidden=false;$('answer-state').hidden=true;currentRun=null;$('details').open=false;$('trace').replaceChildren();reset()}catch(e){feedback(e.message)}finally{busy=false;controls()}}
$('sample').onclick=async()=>{try{const r=await fetch('/api/sample');if(!r.ok)throw Error('Sample image is unavailable.');await upload(new File([await r.blob()],'sample-baseball-fields.png',{type:'image/png'}))}catch(e){feedback(e.message)}};
const viewport=$('viewport');viewport.ondragover=e=>{e.preventDefault();if(!busy)viewport.classList.add('dragover')};viewport.ondragleave=()=>viewport.classList.remove('dragover');viewport.ondrop=e=>{e.preventDefault();viewport.classList.remove('dragover');if(e.dataTransfer.files[0])upload(e.dataTransfer.files[0])};
function transform(){if($('ndvi-overlay'))$('ndvi-overlay').style.transform=`translate(${offset.x}px,${offset.y}px) scale(${scale})`;$('satellite').style.transform=`translate(${offset.x}px,${offset.y}px) scale(${scale})`;$('zoom-label').textContent=`${Math.round(scale*100)}%`}
function reset(){scale=1;offset={x:0,y:0};transform()}$('reset').onclick=reset;$('zoom-in').onclick=()=>{scale=Math.min(5,scale+.25);transform()};$('zoom-out').onclick=()=>{scale=Math.max(1,scale-.25);if(scale===1)offset={x:0,y:0};transform()};
$('satellite').onpointerdown=e=>{pointer={x:e.clientX-offset.x,y:e.clientY-offset.y};e.target.setPointerCapture(e.pointerId)};$('satellite').onpointermove=e=>{if(pointer&&scale>1){offset={x:e.clientX-pointer.x,y:e.clientY-pointer.y};transform()}};$('satellite').onpointerup=$('satellite').onpointercancel=()=>pointer=null;
document.querySelectorAll('.suggestion').forEach(b=>b.onclick=()=>{$('question').value=b.dataset.question;$('question').oninput();$('question').focus()});
function showTrace(run){if(run.statistics){$('trace').replaceChildren();for(const [key,value]of Object.entries(run.statistics)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key.replaceAll('_',' ');dd.textContent=typeof value==='object'?JSON.stringify(value):value;$('trace').append(dt,dd)}return;}const items=[['Task',run.route],['Model',run.model],['Revision',run.revision],['Adapter',run.adapter||'None — baseline'],['Image hash',run.image.sha256],['Generation',`${run.generation_seconds??'—'} s`],['GPU allocated',`${run.peak_allocated_GiB??'—'} GiB`],['Run ID',run.id]];$('trace').replaceChildren();for(const [key,value]of items){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=typeof value==='object'?JSON.stringify(value):value;$('trace').append(dt,dd)}}
$('question-form').onsubmit=async e=>{e.preventDefault();if(busy||!image)return;busy=true;currentRun=null;controls();feedback();$('idle-state').hidden=true;$('answer-state').hidden=true;$('loading').hidden=false;$('stage').textContent='Preparing image';$('elapsed').textContent='Elapsed: 0 s';$('status').textContent='Local model · Processing';$('trace').replaceChildren();const start=Date.now();const timer=setInterval(()=>$('elapsed').textContent=`Elapsed: ${Math.floor((Date.now()-start)/1000)} s`,250);try{const form=new FormData();form.append('image_id',image.id);form.append('question',$('question').value.trim());form.append('mode',$('mode').value);form.append('threshold',$('ndvi-threshold').value);clearEvidence();const job=await api($('mode').value==='ndvi'?'/api/ndvi':'/api/analyze',{method:'POST',body:form});for(;;){const run=await api(`/api/runs/${job.id}`);$('stage').textContent=run.stage;if(run.state==='error')throw Error(run.error);if(run.state==='complete'){currentRun=run;if(run.overlay){$('ndvi-overlay').src=run.overlay;$('ndvi-overlay').hidden=false;$('evidence-controls').hidden=false;$('raster-download').href=run.raster;}$('answer').textContent=run.answer||'The model returned no answer.';$('answer-time').textContent=`${run.seconds.toFixed(2)} s total · ${run.statistics?'Measured NDVI · CPU':run.adapter?'Experimental adapter':'Original model'}`;$('answer-state').hidden=false;showTrace(run);break}await new Promise(r=>setTimeout(r,450))}}catch(e){feedback(e.message);$('idle-state').hidden=false}finally{clearInterval(timer);$('loading').hidden=true;busy=false;controls();status()}};
$('download').onclick=()=>{if(!currentRun)return;const url=URL.createObjectURL(new Blob([JSON.stringify(currentRun,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`satquery-run-${currentRun.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===b));$('explore').hidden=b.dataset.view!=='explore';$('evaluation').hidden=b.dataset.view!=='evaluation';if(b.dataset.view==='evaluation'){loadEvaluation();loadDevelopment()}});
async function loadEvaluation(){try{const s=await api('/api/evaluation');$('eval-score').textContent=`${Math.round(s.accuracy*100)}%`;$('eval-format').textContent=`${s.invalid_format_count??20}/60`;$('eval-rows').replaceChildren();for(const [k,v]of Object.entries(s.per_category)){const tr=document.createElement('tr');for(const value of [({comp:'Comparison',presence:'Presence',rural_urban:'Rural / urban'})[k]||k,`${v.correct}/${v.total}`,`${Math.round(v.correct/v.total*100)}%`]){const td=document.createElement('td');td.textContent=value;tr.append(td)}$('eval-rows').append(tr)}}catch(e){$('eval-error').textContent=e.message}}

async function loadDevelopment(){try{const d=await api('/api/development');$('dev-score').textContent=`Original model: ${d.baseline_dev.correct}/60 → Adapter: ${d.adapted_dev.correct}/60. Format failures: ${d.baseline_dev.invalid_format} → ${d.adapted_dev.invalid_format}.`;$('dev-rows').replaceChildren();for(const k of ['rural_urban','presence','comp']){const tr=document.createElement('tr');for(const v of [k.replace('_',' / '),d.baseline_dev.per_category[k].correct+'/20',d.adapted_dev.per_category[k].correct+'/20']){const td=document.createElement('td');td.textContent=v;tr.append(td)}$('dev-rows').append(tr)}}catch(e){$('dev-score').textContent=e.message}}

// Multispectral controls use the same image geometry and pan/zoom transform.
const geoInfo=document.createElement('p');geoInfo.id='geo-info';geoInfo.className='geo-info';$('viewport').parentElement.append(geoInfo);
const overlay=document.createElement('img');overlay.id='ndvi-overlay';overlay.alt='Pixels meeting the selected NDVI threshold';overlay.hidden=true;$('viewport').append(overlay);
const geoTools=document.createElement('div');geoTools.className='geo-tools';
geoTools.innerHTML='<button type="button" id="scene-sample">Load Dehradun multispectral sample</button><label>NDVI threshold <input id="ndvi-threshold" type="number" min="-1" max="1" step="0.05" value="0.5"></label><div id="evidence-controls" hidden><label><input type="checkbox" id="overlay-toggle" checked> Show NDVI evidence</label><a id="raster-download">Download NDVI GeoTIFF</a></div>';
$('question-form').before(geoTools);
const option=document.createElement('option');option.value='ndvi';option.textContent='NDVI · calibrated red + near-infrared';$('mode').append(option);
$('mode').addEventListener('change',()=>{if($('mode').value==='ndvi'){$('question').value='Calculate NDVI coverage at the selected threshold.';$('question').oninput()}});
$('overlay-toggle').onchange=()=>{$('ndvi-overlay').hidden=!$('overlay-toggle').checked};
function clearEvidence(){$('ndvi-overlay').hidden=true;$('evidence-controls').hidden=true;$('overlay-toggle').checked=true}
$('scene-sample').onclick=async()=>{if(busy)return;try{const r=await fetch('/api/scene-sample');if(!r.ok)throw Error('Multispectral sample unavailable');await upload(new File([await r.blob()],'dehradun-sentinel2-20211125.tif',{type:'image/tiff'}));if(image?.geo?.ndvi_supported){$('mode').value='ndvi';$('mode').dispatchEvent(new Event('change'))}}catch(e){feedback(e.message)}};
