'use strict';
const $=s=>document.querySelector(s);let samples=[],active=false;
const element=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
async function api(url,options){const r=await fetch(url,options);const j=await r.json();if(!r.ok)throw Error(j.detail||'Request failed');return j}
function feedback(text){$('#feedback').hidden=!text;$('#feedback').textContent=text}
function views(items){$('#empty').hidden=true;$('#views').hidden=false;$('#views').replaceChildren();for(const [name,url] of items){const f=element('figure'),i=element('img');i.src=url;i.alt=name;i.onclick=()=>{$('#full').src=url;$('#viewer').showModal()};f.append(i,element('figcaption',name));$('#views').append(f)}}
function selectSample(){const s=samples.find(s=>s.id===$('#sample').value);const single=$('#sample').value==='single';$('#single-fields').hidden=!single;$('#upload-fields').hidden=!!s||single;if(single)$('#question').value='Describe this image.';$('#result').hidden=true;feedback('');if(s){$('#question').value=s.kind==='temporal'?'What changed between these two dates, and where?':s.kind==='water_map'?'Map water using the optical and SAR images together.':'Use the optical and SAR images together to identify land-cover classes.';const files=s.kind==='temporal'?['before.png','after.png']:['optical.png','sar.png'];views(files.map((f,i)=>[s.kind==='temporal'?['Before','After'][i]:['Optical preview','SAR preview'][i],`/api/preview/${s.id}/${f}`]));$('#visual-note').textContent=s.source+' · '+s.benchmark}else{$('#views').hidden=true;$('#empty').hidden=false;$('#visual-note').textContent='Upload a compatible pair. Processing runs locally.'}}
function table(headers,rows){const t=element('table'),head=element('tr');headers.forEach(h=>head.append(element('th',h)));t.append(head);rows.forEach(row=>{const tr=element('tr');row.forEach(v=>tr.append(element('td',v)));t.append(tr)});return t}
function showResult(r){
 $('#result').hidden=false;$('#answer').textContent=r.answer;$('#metrics').replaceChildren(element('span',`${r.seconds.toFixed(2)} s · ${['vqa','ndvi'].includes(r.task)?'Preserved workspace':'CPU'}`));$('#scores').replaceChildren();
 const url=f=>`/api/runs/${r.id}/${f}`;
 if(r.task==='temporal'){
  $('#metrics').append(element('span',`${r.changed_pixels.toLocaleString()} / ${r.denominator_pixels.toLocaleString()} pixels`));
  views([['Before','before.png'],['After','after.png'],['Road change: cyan · building change: gold','change-mask.png'],['Change overlay','overlay.png']].map(([n,f])=>[n,url(f)]));
  $('#scores').append(element('p','Caption: model interpretation. Pixel totals are calculated from the predicted masks.'),table(['Changed class','Pixels'],Object.entries(r.class_pixels||{})));
 }else if(r.task==='water_map'){
  views([['Optical','optical.png'],['SAR display','sar.png'],['Joint water mask','all-water.png'],['Water overlay','water-overlay.png']].map(([n,f])=>[n,url(f)]));
  $('#scores').append(table(['Inputs','Predicted water pixels','Valid-pixel coverage'],['s1','s2','all'].map(k=>[{s1:'SAR only',s2:'Optical only',all:'Joint'}[k],r.water_pixels[k].toLocaleString(),(100*r.water_pixels[k]/r.denominator_pixels).toFixed(2)+'%'])),element('p',`Denominator: ${r.denominator_pixels.toLocaleString()} common finite pixels of ${r.full_image_pixels.toLocaleString()} full-image pixels.`));
 }else if(r.task==='vqa'){views([['Uploaded image',url('input-preview.png')]])}
 else if(r.task==='ndvi'){
  views([['RGB','rgb.png'],['False colour','false-colour.png'],['NDVI overlay','evidence.png'],['Threshold mask','mask.png']].map(([n,f])=>[n,url(f)]));
  const p=element('pre',JSON.stringify(r.statistics,null,2));$('#scores').append(p);
 }else{
  views([['Optical preview','optical.png'],['SAR preview','sar.png']].map(([n,f])=>[n,url(f)]));
  const names=Object.keys(r.scores.all).sort((a,b)=>r.scores.all[b]-r.scores.all[a]);$('#scores').append(element('p','Model scores — not measured accuracy'),table(['Land cover','SAR','Optical','Joint'],names.map(c=>[c,...['s1','s2','all'].map(k=>(r.scores[k][c]*100).toFixed(1)+'%')])));
 }
 $('#visual-note').textContent='Click a view to inspect it. Original inputs, outputs and trace are in the evidence download.';
 $('#download').href=url('evidence.zip');$('#json').href=url('result.json');$('#trace').textContent=JSON.stringify({controller:r.controller,checks:r.input_checks,confidence:r.confidence,tools:r.trace},null,2);$('#limits').replaceChildren(...r.limitations.map(x=>element('li',x)));
}
$('#form').onsubmit=async ev=>{ev.preventDefault();if(active)return;active=true;$('#run').disabled=true;$('#sample').disabled=true;$('#result').hidden=true;const start=Date.now();try{const payload={query:$('#question').value};if($('#sample').value==='single'){const file=$('#single-file').files[0];if(!file)throw Error('Choose an image.');const body=new FormData();body.append('file',file);feedback('Checking the image…');payload.images=[(await api('/api/single-images',{method:'POST',body})).id];payload.threshold=Number($('#threshold').value)}else if($('#sample').value)payload.sample=$('#sample').value;else{payload.images=[];for(const suffix of ['a','b']){const file=$(`#file-${suffix}`).files[0];if(!file)throw Error('Choose both TIFF files.');const body=new FormData();body.append('file',file);body.append('modality',$(`#mode-${suffix}`).value);body.append('date',$(`#date-${suffix}`).value);feedback('Checking uploaded image…');payload.images.push((await api('/api/images',{method:'POST',body})).id)}}feedback('Checking the pair and selecting its specialist…');const j=await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});while(true){await new Promise(r=>setTimeout(r,600));const state=await api(`/api/jobs/${j.id}`);if(state.state==='complete'){showResult(state.result);feedback('Run complete. Evidence and inputs are ready to download.');break}if(state.state==='failed')throw Error(state.error);feedback(`${state.stage} · ${Math.round((Date.now()-start)/1000)} s`)}}catch(e){feedback(e.message)}finally{active=false;$('#run').disabled=false;$('#sample').disabled=false}};
$('#sample').onchange=selectSample;$('#close').onclick=()=>$('#viewer').close();
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem('satquery-theme',t);$('#theme').textContent=t==='dark'?'☀':'☾'}
theme(localStorage.getItem('satquery-theme')||'dark');$('#theme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function tab(evaluation){$('#lab').hidden=evaluation;$('#evaluation').hidden=!evaluation;$('#lab-tab').classList.toggle('active',!evaluation);$('#eval-tab').classList.toggle('active',evaluation)}$('#lab-tab').onclick=()=>tab(false);$('#eval-tab').onclick=()=>tab(true);
function aggregate(rows){const s=rows.reduce((a,m)=>({tp:a.tp+m.tp,fp:a.fp+m.fp,fn:a.fn+m.fn}),{tp:0,fp:0,fn:0});return {f1:2*s.tp/(2*s.tp+s.fp+s.fn),iou:s.tp/(s.tp+s.fp+s.fn)}}
async function boot(){try{const status=await api('/api/status');$('#status').textContent='Local lab · '+status.state;samples=await api('/api/samples');for(const kind of ['temporal','optical_sar','water_map']){const group=element('optgroup');group.label=kind==='temporal'?'Temporal · LEVIR building change':kind==='water_map'?'Water maps · Sen1Floods11':'Optical + SAR · BigEarthNet';for(const s of samples.filter(s=>s.kind===kind)){const o=element('option',s.name);o.value=s.id;group.append(o)}$('#sample').append(group)}$('#sample').value=samples[0]?.id||'';selectSample();const e=await api('/api/evaluation'),container=$('#eval-content');container.append(element('p','Current cross-modal model: '+e.selected_model),...e.notes.map(n=>element('p',n)));const t=e.temporal.filter(r=>r.kind==='public-test-named-demo');const a=aggregate(t.map(r=>r.metrics));container.append(element('h3',`Temporal · ${t.length} public demo crops`),element('p',`Pooled changed-pixel F1 ${(a.f1*100).toFixed(1)}%; IoU ${(a.iou*100).toFixed(1)}%. This measures these masks only.`),table(['Crop','Change IoU','F1','Seconds'],e.temporal.map(r=>[r.sample,r.kind==='same-image-control'?'N/A · '+r.metrics.fp+' false pixels':(r.metrics.iou*100).toFixed(1)+'%',r.kind==='same-image-control'?'N/A':(r.metrics.f1*100).toFixed(1)+'%',r.seconds.toFixed(2)])));container.append(element('h3','Optical–SAR · separate modalities versus joint model'),element('p','Fixed score threshold 0.5. Six validation and six test-labelled public fixtures, all from one Austrian scene. No geographic generalisation claim.'));const rows=[];for(const split of ['validation','test'])for(const kind of ['s1','s2','all']){const r=e.optical_sar.filter(r=>r.split===split);rows.push([split,{s1:'SAR only',s2:'Optical only',all:'Joint optical–SAR'}[kind],(aggregate(r.map(x=>x.metrics[kind])).f1*100).toFixed(1)+'%'])}container.append(table(['Public split','Model','Micro F1'],rows),element('p','The selected ResNet50 joint model beats its matching single-modality models on this small subset. This does not establish fusion superiority on new places or sensors. The earlier ResNet18 trial did not show a consistent joint advantage.'))}catch(e){feedback(e.message)}}boot();

async function resumedEvidence(){try{
 const e=await api('/api/resumed-evaluation'),c=$('#eval-content');
 c.prepend(element('h3','New evidence · temporal descriptions and water maps'));
 const block=element('div');const pct=x=>x==null?'N/A':(100*x).toFixed(2)+'%';
 if(e.water){block.append(element('h3','Water segmentation · same model, three input configurations'),element('p','Official 90-pair test and separate 15-pair Bolivia event holdout. Water F1 and IoU measure predicted pixels; they are not general VQA accuracy.'));
 const rows=[];for(const split of ['test','bolivia'])for(const mode of ['s1','s2','all']){const m=e.water[split].aggregate[mode];rows.push([split,{s1:'SAR only',s2:'Optical only',all:'Joint'}[mode],pct(m.water_f1),pct(m.water_iou)])}block.append(table(['Split','Inputs','Water F1','Water IoU'],rows),element('p','Fusion is not guaranteed to beat optical alone. All three results remain visible.'));}
 if(e.temporal){block.append(element('h3','Temporal · 100 labelled test pairs'),table(['Class','Pixel IoU'],[['Road change',pct(e.temporal.class_iou['1'])],['Building change',pct(e.temporal.class_iou['2'])]]),element('p',`Caption change/no-change agreement: ${e.temporal.caption_changeflag_agreement.correct}/100. This does not score every detail in a caption.`));}
 c.prepend(block);
}catch(e){feedback(e.message)}}resumedEvidence();
